name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TZ: "Asia/Tokyo"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Yarn
        uses: actions/setup-node@v2
        with:
          check-latest: true
          cache: "yarn"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
